### ISSUE TITLE
Consider supporting py 3.8

### ISSUE THREAD

**Issue by bergercookie** [rkhwaja/rtmilk#78]
Hi there, 

Thanks for making this project public.

I'm looking to use `rtmlik` for enabling bidirectional synchronization of rememberthemilk with other task managers like, e.g., taskwarrior in [syncall](https://github.com/bergercookie/syncall) - see [issue](https://github.com/bergercookie/syncall/issues/104)

However rtmilk currently only supports py >= 3.9, and `syncall` supports python >= 3.8 and that's blocking this work.

Could you consider adding suport for 3.8 ?

**Comment by rkhwaja** [comment]
Sorry, no. 3.8 doesn't support [Annotated](https://docs.python.org/3/library/typing.html#typing.Annotated).
